# NOT ACTIVE YET!

git:
  depth: 100

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
  fast_finish: true

env:
  global:
    - CC_ENV=travis-ci

  matrix:
    - CC_BOOT=default

before_install:
  - antcc/bootstrap/install.sh
  - export CC_CLI_HOME="$HOME/.sag/tools/CommandCentral/client"
  - export ANT_HOME="$HOME/.sag/tools/common/lib/ant"
  - export ANTCC_HOME=`pwd`/antcc
  - export PATH=$PATH:$ANTCC_HOME/bin:$ANT_HOME/bin

script:
  - antcc boot -Daccept.license=true
  - antcc up

cache:
  directories:
    - $HOME/Downloads
