language: java
jdk:
  - oraclejdk8
#env:
#  - release=9.12
#  - release=10.1
script:
  - export CC_ENV=travis-ci && export CC_BOOT=default
  - ant boot -Daccept.license=true
  - ~/sag/cc/CommandCentral/client/bin/sagccant credentials masters test installers clean
  - ~/sag/cc/CommandCentral/client/bin/sagccant mirrors mirrors2
  - ~/sag/cc/CommandCentral/client/bin/sagccant mirrors mirrors2 -Drelease=9.12
