version: 1.0.{build}
environment:
  CC_ENV: appveyor
clone_script:
- cmd: >-
    git clone -b release/103oct2018 --recursive https://github.com/SoftwareAG/sagdevops-cc-server.git

    cd sagdevops-cc-server
install:
- ps: bootstrap/install.ps1
# - cmd: choco install ant
cache: C:\Users\appveyor\Downloads
build_script:
- cmd: >-
    ant boot -Daccept.license=true

    ant up
test_script:
- cmd: ant test
deploy: off
