version: "3.2"

services:
  cc:
    image: softwareag/commandcentral:10.1.0.1-server
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8092:8092" # for master mirror     
    environment:
      - CC_PASSWORD
      
  dev1:   # this is main test node
    image: softwareag/commandcentral:10.1.0.1-node
    ports: # export all known ports for easy testing, but dont statically bind them to allow CI
      - target: 5555 # IS
        #published: 5555
      - target: 9000 # UM
        #published: 9000        
      - target: 8585 # UM
        #published: 8585       
      #- "8080:8080" # ?
      - target: 8072 # Applatform
        #published: 8072       
    environment:
      - CC_AUTO_REGISTER=0

  dev2: # this is supporting node
    image: softwareag/commandcentral:10.1.0.1-node
    environment:
      - CC_AUTO_REGISTER=0

  devoracle:
    image: daerepository03.eur.ad.sag:4443/ccdevops/oracle:11
    ports: 
      - target: 1521 # Oracle port
        #published: 1521      
    environment: 
      - ORACLE_ALLOW_REMOTE=true

  init:
    image: softwareag/commandcentral:10.1.0.1-server
    volumes: 
      - ./:/src 
      - ./clients/docker.properties:/root/.sag/cc.properties
    environment: 
      - CC_SERVER=cc
      - CC_PASSWORD
      - EMPOWER_USR
      - EMPOWER_PSW
    command: sagccant -Denv=docker credentials masters layers licenses
    depends_on: 
      - cc

  initdev:
    image: softwareag/commandcentral:10.1.0.1-server
    volumes: 
      - ./:/src 
      - ./clients/docker.properties:/root/.sag/cc.properties
    environment: 
      - CC_SERVER=cc
      - CC_PASSWORD
    command: sagccant nodes oracledb -Denv=docker
    depends_on: 
      - cc
      - devoracle
      - dev1
      - dev2
